config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :posts
  get 'pages/home'
  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'posts/most_viewed_users', to: 'posts#most_viewed_users'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check




  # Defines the root path route ("/")
  root "pages#home"
end

app/views/layouts/_alerts.html.erb

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_navbar.html.erb
<div class="p-3 mb-2 bg-secondary text-white">
    <ul class="nav justify-content-evenly">
        <li class="nav-item">
            <%= link_to "Domov", root_path, class:'nav-link', class:"btn btn-dark"%>
        </li>
        <li class="nav-item">
            <%= link_to "Příspěvky", posts_path, class:'nav-link', class:"btn btn-dark"%>
        </li>
        <li>
            <%= link_to "Nejoblíbenější uživatelé", posts_most_viewed_users_path, class:'nav-link', class:"btn btn-dark"%>
        </li>
        <li>
            <%= link_to "Nový příspěvek", new_post_path, class:'nav-link', class:"btn btn-success"%>
        </li>
        <li>
            <%= render 'user/session_manager'%>
        </li>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar' %>
      <%= render 'layouts/alerts'%>
    </header>
      <main>
        <%= yield %>
      </ma>
  </body>
</html>
<script>
  $(document).on('ready page:load', function () {
    $('#post_tag_ids').chosen({
      allow_single_deselect: true,
      width: '100%'
    })
  });
</script>